stages:
  - build
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_windows:
  stage: build
  tags:
    - custom-windows
  script:
    # - py build.py
    # - py package.py
    - for /f "delims=" %%x in (ungoogled-chromium\chromium_version.txt) do set CHROMIUM_VERSION=%%x
    - echo RELEASE_NAME=%CHROMIUM_VERSION% >> variables.env
  artifacts:
    paths:
      - 'build/ungoogled-chromium*.exe'
      - 'build/ungoogled-chromium*.zip'
    expire_in: 14 days
    reports:
      dotenv: variables.env

release_windows:
  stage: release
  tags:
    - docker
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_windows
      artifacts: true
  script:
    - echo Running release job for %RELEASE_NAME%.
  release:
    name: ${RELEASE_NAME}_${CI_COMMIT_SHA}
    description: Release ${RELEASE_NAME} from commit ${CI_COMMIT_SHA}
    tag_name: ${RELEASE_NAME}_${CI_COMMIT_SHA}
    ref: ${CI_COMMIT_SHA}
